// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

heizige.kk.khatkit.app.data.model.Conversation
heizige.kk.khatkit.app.data.model.MessageNode
heizige.kk.khatkit.ai.ui.UIMessage
heizige.kk.khatkit.ai.ui.UIMessageChoice
heizige.kk.khatkit.ai.ui.MessageChunk
heizige.kk.khatkit.ai.ui.UIMessageAnnotation
heizige.kk.khatkit.ai.ui.ToolApprovalState
heizige.kk.khatkit.ai.core.TokenUsage